## 1.1 - Normalization

In [4]:
import numpy as np

In [3]:
#!pip install --user numpy==1.23.0

In [4]:
#pip list

Package                       Version
----------------------------- --------------------
aiobotocore                   2.4.2
aiohttp                       3.8.1
aioitertools                  0.11.0
aiosignal                     1.2.0
alabaster                     0.7.12
anaconda-client               1.9.0
anaconda-navigator            2.2.0
anaconda-project              0.10.2
anyio                         3.5.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.2
astroid                       2.6.6
astropy                       5.0.4
asttokens                     2.0.5
async-timeout                 4.0.1
atomicwrites                  1.4.0
attrs                         21.4.0
autograd                      1.7.0
Automat                       20.2.0
autopep8                      1.6.0
autoray                       0.6.12
Babel                         2.9.1
backcall                      0.2.0
bac

pyparsing                     3.0.4
pyreadline                    2.1
pyrsistent                    0.18.0
PySocks                       1.7.1
pytest                        7.1.1
python-dateutil               2.8.2
python-lsp-black              1.0.0
python-lsp-jsonrpc            1.0.0
python-lsp-server             1.2.4
python-slugify                5.0.2
python-snappy                 0.6.0
python-upwork-oauth2          3.1.0
pytz                          2021.3
pyviz-comms                   2.0.2
PyWavelets                    1.3.0
pywin32                       302
pywin32-ctypes                0.2.0
pywinpty                      2.0.2
PyYAML                        6.0
pyzmq                         22.3.0
QDarkStyle                    3.0.2
qstylizer                     0.1.10
QtAwesome                     1.0.3
qtconsole                     5.3.0
QtPy                          2.0.1
queuelib                      1.5.0
regex                         2022.3.15
requests                  

In [5]:
def normalize_state(alpha, beta):
    """Compute a normalized quantum state given arbitrary amplitudes.

    Args:
        alpha (complex): The amplitude associated with the |0> state.
        beta (complex): The amplitude associated with the |1> state.

    Returns:
        np.array[complex]: A vector (numpy array) with 2 elements that represents
        a normalized quantum state.
    """
    #Given that a^2+b^2=1

    k = 1/np.sqrt(abs(alpha)**2 + abs(beta)**2)

    alpha_k = k*alpha
    beta_k = k*beta

    # CREATE A VECTOR [a', b'] BASED ON alpha AND beta SUCH THAT |a'|^2 + |b'|^2 = 1
    ket_norm = np.array([alpha_k, beta_k])

    # RETURN A VECTOR
    return ket_norm

In [10]:
normalize_state(1+1j, 1-1j)

array([0.5+0.5j, 0.5-0.5j])

## 1.2 - Inner product ##

In [11]:
def inner_product(state_1, state_2):
    """Compute the inner product between two states.

    Args:
        state_1 (np.array[complex]): A normalized quantum state vector
        state_2 (np.array[complex]): A second normalized quantum state vector

    Returns:
        complex: The value of the inner product <state_1 | state_2>.
    """
    #Mathematical representation of qubits
    #Handle negation of imaginary numbers with conjugation operation
    conj_state_1 = np.array([complex(element.real, -element.imag) for element in state_1])
    
    inn_prod = np.dot(conj_state_1, state_2)
    
    return inn_prod

In [12]:
# Test your results with this code
ket_0 = np.array([1, 0])
ket_1 = np.array([0, 1])

print(f"<0|0> = {inner_product(ket_0, ket_0)}")
print(f"<0|1> = {inner_product(ket_0, ket_1)}")
print(f"<1|0> = {inner_product(ket_1, ket_0)}")
print(f"<1|1> = {inner_product(ket_1, ket_1)}")

<0|0> = (1+0j)
<0|1> = 0j
<1|0> = 0j
<1|1> = (1+0j)


## 1.3 - Sampling outcomes

In [13]:
def measure_state(state, num_meas):
    """Simulate a quantum measurement process.

    Args:
        state (np.array[complex]): A normalized qubit state vector.
        num_meas (int): The number of measurements to take

    Returns:
        np.array[int]: A set of num_meas samples, 0 or 1, chosen according to the probability
        distribution defined by the input state.
    """
    
    # COMPUTE THE MEASUREMENT OUTCOME PROBABILITIES
    p_0 = abs(state[0])**2
    p_1 = abs(state[1])**2
    # RETURN A LIST OF SAMPLE MEASUREMENT OUTCOMES
    outcomes = np.random.choice([0,1], p=[p_0, p_1], size=num_meas)
    return outcomes

In [14]:
example_state =  np.array([0.8, 0.6])
measure_state(example_state, 10)

array([0, 0, 0, 1, 0, 1, 1, 1, 0, 0])

## 1.4 - Quantum operation ##

In [15]:
U = np.array([[1, 1], [1, -1]]) / np.sqrt(2)


def apply_u(state):
    """Apply a quantum operation.

    Args:
        state (np.array[complex]): A normalized quantum state vector.

    Returns:
        np.array[complex]: The output state after applying U.
    """

    # APPLY U TO THE INPUT STATE AND RETURN THE NEW STATE
    u_op = np.dot(U, state)
    return u_op

In [16]:
example_state =  np.array([0.8, 0.6])
apply_u(example_state)

array([0.98994949, 0.14142136])

## 1.5 - Quantum algorithm ##

In [18]:
U = np.array([[1, 1], [1, -1]]) / np.sqrt(2)


def initialize_state():
    """Prepare a qubit in state |0>.

    Returns:
        np.array[float]: the vector representation of state |0>.
    """

    state = np.array([1,0])

    # PREPARE THE STATE |0>
    return state


def apply_u(state):
    """Apply a quantum operation."""
    return np.dot(U, state)


def measure_state(state, num_meas):
    """Measure a quantum state num_meas times."""
    p_alpha = np.abs(state[0]) ** 2
    p_beta = np.abs(state[1]) ** 2
    meas_outcome = np.random.choice([0, 1], p=[p_alpha, p_beta], size=num_meas)
    return meas_outcome


def quantum_algorithm():
    """Use the functions above to implement the quantum algorithm described above.

    Try and do so using three lines of code or less!

    Returns:
        np.array[int]: the measurement results after running the algorithm 100 times
    """

    state = initialize_state()
    u_op = apply_u(state)
    meas_100 = measure_state(u_op, 100)
    
    # PREPARE THE STATE, APPLY U, THEN TAKE 100 MEASUREMENT SAMPLES
    return meas_100

In [19]:
quantum_algorithm()

array([0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1])